# Generated by Django 4.2.7 on 2023-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnosis", "0004_disease_diseaselevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseaselevel",
            name="percent",
            field=models.FloatField(default=0),
        ),
    ]
