# Generated by Django 4.2.7 on 2023-11-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnosis", "0005_diseaselevel_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="percent",
            field=models.FloatField(default=0),
        ),
    ]
