# Generated by Django 4.2.7 on 2023-11-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnosis", "0006_diagnosis_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseaselevel",
            name="treatment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
